/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  chege
 * Created: Dec 5, 2016
 */
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (1,'Vernon','Harper','egestas.rhoncus.Proin@massaQuisqueporttitor.org','Financial Analysis'),(2,'Murphy','Holmes','faucibus.orci.luctus@Duisac.net','Financial Analysis'),(3,'Reece','Jason','tincidunt.dui@ultricessit.co.uk','Computer Science'),(4,'Orson','Armando','nascetur@conguea.com','Computer Science'),(5,'Cullen','Craig','imperdiet.ullamcorper@nonenimMauris.co.uk','Disaster Management'),(6,'Harper','Rashad','vestibulum@ridiculusmus.edu','Disaster Management'),(7,'Roth','Grant','eu.tellus@anuncIn.edu','Mechanical Engineering'),(8,'Jermaine','Alden','scelerisque.sed@senectuset.org','Law'),(9,'Sebastian','Jesse','faucibus@sed.co.uk','Medicine'),(10,'Todd','Beck','Fusce.dolor.quam@commodoauctor.org','Financial Analysis');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (11,'Giacomo','Raphael','magnis.dis@idmagnaet.com','Medicine'),(12,'Chadwick','Lawrence','turpis.non.enim@sociisnatoque.com','Criminology'),(13,'Zachary','Vance','In.tincidunt.congue@Quisque.com','Criminology'),(14,'Denton','Walker','Integer.sem@iaculisodioNam.edu','Mechanical Engineering'),(15,'Hakeem','Fitzgerald','accumsan@luctuset.edu','Financial Analysis'),(16,'Jakeem','Philip','montes.nascetur.ridiculus@loremDonec.com','Mechanical Engineering'),(17,'Amal','Emery','turpis.egestas.Aliquam@fermentum.net','Computer Science'),(18,'Reed','Wylie','Suspendisse.aliquet.sem@atrisus.org','Medicine'),(19,'Lev','Philip','dolor.elit.pellentesque@enimEtiamimperdiet.ca','Computer Science'),(20,'Lamar','Berk','leo.Vivamus@sit.org','Medicine');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (21,'Nathaniel','Colton','hendrerit@et.co.uk','Medicine'),(22,'Kennan','Jacob','vel.vulputate@vitaedolorDonec.ca','Financial Analysis'),(23,'Omar','Colt','venenatis.a@Pellentesque.co.uk','Mechanical Engineering'),(24,'Tanek','Scott','Sed.malesuada@porttitoreros.ca','Criminology'),(25,'Paki','Samson','ornare@Mauriseuturpis.edu','Law'),(26,'James','Jonah','Nullam@Cras.net','Mechanical Engineering'),(27,'Cade','Vernon','pharetra.sed@Aliquamvulputateullamcorper.ca','Mechanical Engineering'),(28,'Quentin','Chadwick','sed.turpis.nec@risusQuisque.ca','Mechanical Engineering'),(29,'Arden','Abel','consequat.enim@ultricessit.com','Law'),(30,'Lars','Keith','Fusce@Quisquefringillaeuismod.org','Medicine');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (31,'Emmanuel','Gavin','ornare.libero@perinceptoshymenaeos.co.uk','Criminology'),(32,'Noah','Oren','Proin.vel@placerat.org','Law'),(33,'Mason','Barry','id@incursus.co.uk','Law'),(34,'Elliott','Brady','Vestibulum@adlitora.net','Law'),(35,'Nero','Brett','amet.ante@sit.com','Disaster Management'),(36,'Elvis','Abraham','neque@interdumfeugiat.net','Disaster Management'),(37,'Kieran','Ross','magnis.dis.parturient@laciniaorci.edu','Disaster Management'),(38,'Noah','Merrill','et@ipsum.net','Medicine'),(39,'Peter','Noble','turpis@sagittisplaceratCras.ca','Computer Science'),(40,'Axel','Bradley','ridiculus.mus@tempus.net','Mechanical Engineering');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (41,'Hashim','Chancellor','at.pretium@eleifendvitae.net','Medicine'),(42,'Alan','Connor','vel.turpis.Aliquam@metus.org','Mechanical Engineering'),(43,'Abel','Rudyard','orci.luctus.et@posuere.com','Computer Science'),(44,'Cedric','Zeus','Quisque.tincidunt@nullaanteiaculis.co.uk','Law'),(45,'Boris','Kato','dictum@tortorInteger.org','Medicine'),(46,'Walter','Phelan','diam@nectellusNunc.edu','Law'),(47,'Preston','Branden','sagittis.semper@urnaNullam.net','Criminology'),(48,'Kane','Alec','dignissim.Maecenas.ornare@adui.edu','Law'),(49,'Igor','Ezra','cursus.non.egestas@laciniaorci.net','Criminology'),(50,'Yoshio','Kato','Vivamus.rhoncus@semutcursus.ca','Disaster Management');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (51,'Fletcher','Vance','orci.lacus@hendreritDonecporttitor.net','Computer Science'),(52,'Burton','Merrill','mauris@malesuada.ca','Law'),(53,'Rafael','Vladimir','mauris.ipsum.porta@sit.ca','Law'),(54,'Dolan','Hyatt','augue.malesuada@Pellentesqueut.net','Computer Science'),(55,'Driscoll','Russell','Lorem.ipsum.dolor@eu.co.uk','Computer Science'),(56,'Boris','Dexter','purus@mollis.co.uk','Law'),(57,'Maxwell','Tarik','pharetra.Quisque.ac@facilisisSuspendisse.edu','Criminology'),(58,'Nero','Ulysses','inceptos.hymenaeos.Mauris@Proin.edu','Financial Analysis'),(59,'Chase','Laith','ridiculus.mus.Donec@netus.org','Mechanical Engineering'),(60,'Dominic','Malcolm','mi.felis.adipiscing@liberoettristique.edu','Criminology');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (61,'Ross','Hedley','Ut.tincidunt.vehicula@nuncidenim.edu','Criminology'),(62,'Abel','Garrett','rhoncus@sociisnatoquepenatibus.ca','Financial Analysis'),(63,'Nero','Clarke','eget.metus.In@disparturientmontes.org','Computer Science'),(64,'Thane','Carl','ut.nulla@netuset.co.uk','Criminology'),(65,'Jerome','Jackson','ac.turpis@facilisislorem.net','Computer Science'),(66,'Tate','Martin','ante.blandit@semeget.org','Law'),(67,'Caldwell','Daniel','lobortis@nequevenenatislacus.net','Medicine'),(68,'Lucian','Holmes','Cras@lorem.org','Medicine'),(69,'Akeem','Herrod','vel.venenatis@Nullamvelit.com','Disaster Management'),(70,'Vance','Colin','quam.vel.sapien@vellectusCum.org','Disaster Management');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (71,'Austin','Jelani','Nulla@nuncid.net','Medicine'),(72,'Jackson','Honorato','In@vestibulumlorem.com','Criminology'),(73,'Lee','Acton','rutrum@mattis.org','Mechanical Engineering'),(74,'Aquila','Sylvester','Aliquam.ultrices.iaculis@duiquisaccumsan.co.uk','Criminology'),(75,'Baker','Cairo','fermentum@diam.com','Financial Analysis'),(76,'Samuel','Kibo','semper@enimcommodohendrerit.co.uk','Criminology'),(77,'Byron','Warren','enim.Etiam.imperdiet@sitamet.ca','Mechanical Engineering'),(78,'Declan','Barclay','Proin.nisl.sem@Aliquamnecenim.org','Mechanical Engineering'),(79,'Robert','Cullen','in.dolor@pede.co.uk','Disaster Management'),(80,'Troy','Simon','Cras.vulputate.velit@ornare.org','Criminology');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (81,'Tiger','Wylie','risus.quis.diam@Proin.ca','Disaster Management'),(82,'Herrod','Adam','hendrerit.neque@a.co.uk','Medicine'),(83,'Yuli','Griffin','ipsum.non@vitae.co.uk','Criminology'),(84,'Chancellor','Ali','ultrices@Nullam.net','Medicine'),(85,'Charles','Randall','ipsum.porta.elit@morbitristique.net','Law'),(86,'Lucius','Gage','auctor.vitae.aliquet@parturient.org','Disaster Management'),(87,'Richard','Dane','Nulla.eget@musDonecdignissim.co.uk','Mechanical Engineering'),(88,'Addison','Jermaine','est.Mauris@et.co.uk','Disaster Management'),(89,'Acton','Elliott','sem.eget@posuerecubiliaCurae.ca','Medicine'),(90,'Channing','Howard','est.congue@velit.com','Medicine');
INSERT INTO student (id,first_name,last_name,email,programme) VALUES (91,'Darius','Nehru','risus.varius.orci@sitamet.edu','Medicine'),(92,'Walter','Arsenio','a.ultricies@duiFusce.edu','Financial Analysis'),(93,'Dieter','Matthew','a@pretium.ca','Mechanical Engineering'),(94,'Evan','Yoshio','sapien.gravida.non@noncursus.com','Financial Analysis'),(95,'Hamilton','Dennis','luctus.lobortis@nonbibendumsed.com','Mechanical Engineering'),(96,'Gavin','Driscoll','lacinia.mattis@risusDonec.net','Medicine'),(97,'Brendan','Allistair','Nunc.laoreet@Sed.ca','Computer Science'),(98,'Gary','Robert','molestie@vitaesemper.ca','Computer Science'),(99,'Fletcher','Brenden','semper@nequesed.co.uk','Computer Science'),(100,'Oscar','Barclay','non.ante.bibendum@risusDonecegestas.edu','Mechanical Engineering');
